### ISSUE TITLE
Example not working out of the box.

### ISSUE THREAD

**Issue by muhdhish** [ariffinzulkifli/FavoriotHTTP#2]
Using latest Arduino IDE V1.8.16.

C:\Users\teamm\Documents\Arduino\libraries\FavoriotHTTP-master\FavoriotHTTPS.cpp: In member function 'void FavoriotHTTPS::begin(const char*, const char*, const char*)':
C:\Users\teamm\Documents\Arduino\libraries\FavoriotHTTP-master\FavoriotHTTPS.cpp:41:106: error: no matching function for call to 'begin(const char [28], const char [60])'
   41 |   http.begin("https://apiv2.favoriot.com/", "25 20 4D 06 3C 95 69 5E 2D 25 79 59 E9 21 7B B7 6A 84 F5 5C");
      |                                                                                                          ^
In file included from C:\Users\teamm\Documents\Arduino\libraries\FavoriotHTTP-master\FavoriotHTTPS.h:14,
                 from C:\Users\teamm\Documents\Arduino\libraries\FavoriotHTTP-master\FavoriotHTTPS.cpp:8:
C:\Users\teamm\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.0\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:166:10: note: candidate: 'bool HTTPClient::begin(String, uint16_t, String)' (near match)
  166 |     bool begin(String host, uint16_t port, String uri = "/")  __attribute__ ((error("obsolete API, use ::begin(WiFiClient, host, port, uri)")));
      |          ^~~~~
C:\Users\teamm\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.0\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:166:10: note:   conversion of argument 2 would be ill-formed:
C:\Users\teamm\Documents\Arduino\libraries\FavoriotHTTP-master\FavoriotHTTPS.cpp:41:45: error: invalid conversion from 'const char*' to 'uint16_t' {aka 'short unsigned int'} [-fpermissive]
   41 |   http.begin("https://apiv2.favoriot.com/", "25 20 4D 06 3C 95 69 5E 2D 25 79 59 E9 21 7B B7 6A 84 F5 5C");
      |                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                             |
      |                                             const char*
In file included from C:\Users\teamm\Documents\Arduino\libraries\FavoriotHTTP-master\FavoriotHTTPS.h:14,
                 from C:\Users\teamm\Documents\Arduino\libraries\FavoriotHTTP-master\FavoriotHTTPS.cpp:8:
C:\Users\teamm\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.0\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:167:10: note: candidate: 'bool HTTPClient::begin(String, const uint8_t*)' (near match)
  167 |     bool begin(String url, const uint8_t httpsFingerprint[20])  __attribute__ ((error("obsolete API, use ::begin(WiFiClientSecure, ...)")));
      |          ^~~~~
C:\Users\teamm\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.0\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:167:10: note:   conversion of argument 2 would be ill-formed:
C:\Users\teamm\Documents\Arduino\libraries\FavoriotHTTP-master\FavoriotHTTPS.cpp:41:45: error: invalid conversion from 'const char*' to 'const uint8_t*' {aka 'const unsigned char*'} [-fpermissive]
   41 |   http.begin("https://apiv2.favoriot.com/", "25 20 4D 06 3C 95 69 5E 2D 25 79 59 E9 21 7B B7 6A 84 F5 5C");
      |                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                             |
      |                                             const char*
C:\Users\teamm\Documents\Arduino\libraries\FavoriotHTTP-master\FavoriotHTTPS.cpp: In member function 'void FavoriotHTTPS::dataStreamEnd()':
C:\Users\teamm\Documents\Arduino\libraries\FavoriotHTTP-master\FavoriotHTTPS.cpp:87:116: error: no matching function for call to 'begin(const char [38], const char [60])'
   87 |   http.begin("https://apiv2.favoriot.com/v2/streams", "25 20 4D 06 3C 95 69 5E 2D 25 79 59 E9 21 7B B7 6A 84 F5 5C");
      |                                                                                                                    ^
In file included from C:\Users\teamm\Documents\Arduino\libraries\FavoriotHTTP-master\FavoriotHTTPS.h:14,
                 from C:\Users\teamm\Documents\Arduino\libraries\FavoriotHTTP-master\FavoriotHTTPS.cpp:8:
C:\Users\teamm\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.0\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:166:10: note: candidate: 'bool HTTPClient::begin(String, uint16_t, String)' (near match)
  166 |     bool begin(String host, uint16_t port, String uri = "/")  __attribute__ ((error("obsolete API, use ::begin(WiFiClient, host, port, uri)")));
      |          ^~~~~
C:\Users\teamm\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.0\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:166:10: note:   conversion of argument 2 would be ill-formed:
C:\Users\teamm\Documents\Arduino\libraries\FavoriotHTTP-master\FavoriotHTTPS.cpp:87:55: error: invalid conversion from 'const char*' to 'uint16_t' {aka 'short unsigned int'} [-fpermissive]
   87 |   http.begin("https://apiv2.favoriot.com/v2/streams", "25 20 4D 06 3C 95 69 5E 2D 25 79 59 E9 21 7B B7 6A 84 F5 5C");
      |                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                       |
      |                                                       const char*
In file included from C:\Users\teamm\Documents\Arduino\libraries\FavoriotHTTP-master\FavoriotHTTPS.h:14,
                 from C:\Users\teamm\Documents\Arduino\libraries\FavoriotHTTP-master\FavoriotHTTPS.cpp:8:
C:\Users\teamm\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.0\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:167:10: note: candidate: 'bool HTTPClient::begin(String, const uint8_t*)' (near match)
  167 |     bool begin(String url, const uint8_t httpsFingerprint[20])  __attribute__ ((error("obsolete API, use ::begin(WiFiClientSecure, ...)")));
      |          ^~~~~
C:\Users\teamm\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.0\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:167:10: note:   conversion of argument 2 would be ill-formed:
C:\Users\teamm\Documents\Arduino\libraries\FavoriotHTTP-master\FavoriotHTTPS.cpp:87:55: error: invalid conversion from 'const char*' to 'const uint8_t*' {aka 'const unsigned char*'} [-fpermissive]
   87 |   http.begin("https://apiv2.favoriot.com/v2/streams", "25 20 4D 06 3C 95 69 5E 2D 25 79 59 E9 21 7B B7 6A 84 F5 5C");
      |                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                       |
      |                                                       const char*
C:\Users\teamm\Documents\Arduino\libraries\FavoriotHTTP-master\FavoriotHTTP.cpp: In member function 'void FavoriotHTTP::begin(const char*, const char*, const char*)':
C:\Users\teamm\Documents\Arduino\libraries\FavoriotHTTP-master\FavoriotHTTP.cpp:41:13: error: call to 'HTTPClient::begin' declared with attribute error: obsolete API, use ::begin(WiFiClient, url)
   41 |   http.begin("http://apiv2.favoriot.com/");
      |   ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Users\teamm\Documents\Arduino\libraries\FavoriotHTTP-master\FavoriotHTTP.cpp: In member function 'void FavoriotHTTP::dataStreamEnd()':
C:\Users\teamm\Documents\Arduino\libraries\FavoriotHTTP-master\FavoriotHTTP.cpp:87:13: error: call to 'HTTPClient::begin' declared with attribute error: obsolete API, use ::begin(WiFiClient, url)
   87 |   http.begin("http://apiv2.favoriot.com/v2/streams");
      |   ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
exit status 1
Error compiling for board NodeMCU 0.9 (ESP-12 Module).

**Comment by ariffinzulkifli** [comment]
I am sorry for the late update. I just update the library to support both ESP8266 and ESP32.
